// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Unit tests for ClarificationPolicy: every exclusion of the spec (no need, customer, not planning
/// relevant, switch off, auto-generated mail, open clarification, rate limit, missing personal
/// contact), the release gate (global autonomy level at least Assisted and kill switch off, otherwise
/// Suggest) and the order in which those checks apply.
/// </summary>

using Klacks.Api.Domain.Constants;
using Klacks.Api.Domain.Models.Inbound;
using Klacks.Api.Domain.Services.Inbound;

namespace Klacks.UnitTest.Domain.Services.Inbound;

[TestFixture]
public class ClarificationPolicyTests
{
    private static ClarificationPolicyFacts Facts() => new(
        NeedsClarification: true,
        ClientType: EntityTypeEnum.Employee,
        Intent: EmailIntent.Other,
        FeatureEnabled: true,
        IsAutoGenerated: false,
        HasOpenClarification: false,
        QuestionsAskedInRateWindow: 0,
        KillSwitchActive: false,
        GlobalAutonomyLevel: AutonomyLevel.Assisted,
        HasPersonalReplyTarget: true);

    [Test]
    public void AllConditionsMet_Asks()
    {
        ClarificationPolicy.Decide(Facts()).ShouldBe(ClarificationDecision.Ask);
    }

    [Test]
    public void ExternEmployee_Asks()
    {
        ClarificationPolicy.Decide(Facts() with { ClientType = EntityTypeEnum.ExternEmp }).ShouldBe(ClarificationDecision.Ask);
    }

    [TestCase(EmailIntent.WorkCancellation)]
    [TestCase(EmailIntent.VacationRequest)]
    [TestCase(EmailIntent.DayOffWish)]
    [TestCase(EmailIntent.AvailabilityAnnouncement)]
    [TestCase(EmailIntent.ShiftPreference)]
    [TestCase(EmailIntent.Other)]
    public void PlanningRelevantIntent_Asks(EmailIntent intent)
    {
        ClarificationPolicy.Decide(Facts() with { Intent = intent }).Kind.ShouldBe(ClarificationDecisionKind.Ask);
    }

    [Test]
    public void NoNeed_Skips()
    {
        ClarificationPolicy.Decide(Facts() with { NeedsClarification = false })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.NotNeeded));
    }

    [Test]
    public void Customer_Skips()
    {
        ClarificationPolicy.Decide(Facts() with { ClientType = EntityTypeEnum.Customer })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.NotEmployee));
    }

    [TestCase(EmailIntent.CustomerMessage)]
    [TestCase(EmailIntent.Unknown)]
    public void NotPlanningRelevantIntent_Skips(EmailIntent intent)
    {
        ClarificationPolicy.Decide(Facts() with { Intent = intent })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.NotPlanningRelevant));
    }

    [Test]
    public void SwitchOff_Skips()
    {
        ClarificationPolicy.Decide(Facts() with { FeatureEnabled = false })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.FeatureDisabled));
    }

    [Test]
    public void AutoGeneratedMail_Skips()
    {
        ClarificationPolicy.Decide(Facts() with { IsAutoGenerated = true })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.AutoGeneratedEmail));
    }

    [Test]
    public void OpenClarification_Skips()
    {
        ClarificationPolicy.Decide(Facts() with { HasOpenClarification = true })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.OpenClarificationExists));
    }

    [Test]
    public void RateLimitReached_Skips()
    {
        ClarificationPolicy.Decide(Facts() with { QuestionsAskedInRateWindow = InboundClarificationConstants.MaxQuestionsPerRateLimitWindow })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.RateLimited));
    }

    [Test]
    public void BelowRateLimit_Asks()
    {
        ClarificationPolicy.Decide(Facts() with { QuestionsAskedInRateWindow = InboundClarificationConstants.MaxQuestionsPerRateLimitWindow - 1 })
            .ShouldBe(ClarificationDecision.Ask);
    }

    [Test]
    public void GlobalLevelPropose_Suggests()
    {
        ClarificationPolicy.Decide(Facts() with { GlobalAutonomyLevel = AutonomyLevel.Propose })
            .ShouldBe(ClarificationDecision.Suggest);
    }

    [TestCase(AutonomyLevel.Autonomous)]
    [TestCase(AutonomyLevel.FullyAutonomous)]
    public void GlobalLevelAboveAssisted_Asks(AutonomyLevel level)
    {
        ClarificationPolicy.Decide(Facts() with { GlobalAutonomyLevel = level }).ShouldBe(ClarificationDecision.Ask);
    }

    [Test]
    public void KillSwitchActive_Suggests()
    {
        ClarificationPolicy.Decide(Facts() with { KillSwitchActive = true, GlobalAutonomyLevel = AutonomyLevel.FullyAutonomous })
            .ShouldBe(ClarificationDecision.Suggest);
    }

    [Test]
    public void NoPersonalContact_Skips()
    {
        ClarificationPolicy.Decide(Facts() with { HasPersonalReplyTarget = false })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.NoPersonalReplyTarget));
    }

    [Test]
    public void NoPersonalContactAtLevelPropose_StillSuggests()
    {
        ClarificationPolicy.Decide(Facts() with { HasPersonalReplyTarget = false, GlobalAutonomyLevel = AutonomyLevel.Propose })
            .ShouldBe(ClarificationDecision.Suggest);
    }

    [Test]
    public void SwitchOffWinsOverSuggest()
    {
        ClarificationPolicy.Decide(Facts() with { FeatureEnabled = false, GlobalAutonomyLevel = AutonomyLevel.Propose })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.FeatureDisabled));
    }

    [Test]
    public void AutoGeneratedMailWinsOverSuggest()
    {
        ClarificationPolicy.Decide(Facts() with { IsAutoGenerated = true, KillSwitchActive = true })
            .ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.AutoGeneratedEmail));
    }

    [TestCaseSource(nameof(HardExclusionCases))]
    public void HardExclusion_WinsOverReleaseGate(ClarificationPolicyFacts facts, ClarificationSkipReason expectedReason)
    {
        var decision = ClarificationPolicy.Decide(facts);

        decision.ShouldBe(ClarificationDecision.Skip(expectedReason));
        decision.Kind.ShouldNotBe(ClarificationDecisionKind.Suggest);
    }

    private static IEnumerable<TestCaseData> HardExclusionCases()
    {
        (string Name, ClarificationPolicyFacts Facts, ClarificationSkipReason Reason)[] exclusions =
        {
            ("NeedsClarificationFalse", Facts() with { NeedsClarification = false }, ClarificationSkipReason.NotNeeded),
            ("Customer", Facts() with { ClientType = EntityTypeEnum.Customer }, ClarificationSkipReason.NotEmployee),
            ("NotPlanningRelevantIntent", Facts() with { Intent = EmailIntent.Unknown }, ClarificationSkipReason.NotPlanningRelevant),
            ("FeatureDisabled", Facts() with { FeatureEnabled = false }, ClarificationSkipReason.FeatureDisabled),
            ("AutoGenerated", Facts() with { IsAutoGenerated = true }, ClarificationSkipReason.AutoGeneratedEmail),
            ("OpenClarification", Facts() with { HasOpenClarification = true }, ClarificationSkipReason.OpenClarificationExists),
            ("RateLimitReached", Facts() with { QuestionsAskedInRateWindow = InboundClarificationConstants.MaxQuestionsPerRateLimitWindow }, ClarificationSkipReason.RateLimited),
        };

        (string Name, Func<ClarificationPolicyFacts, ClarificationPolicyFacts> Apply)[] gates =
        {
            ("Propose", f => f with { GlobalAutonomyLevel = AutonomyLevel.Propose }),
            ("KillSwitchActive", f => f with { KillSwitchActive = true }),
        };

        foreach (var exclusion in exclusions)
        {
            foreach (var gate in gates)
            {
                yield return new TestCaseData(gate.Apply(exclusion.Facts), exclusion.Reason)
                    .SetName($"HardExclusion_{exclusion.Name}_{gate.Name}_Skips");
            }
        }
    }

    [Test]
    public void AllEmailIntentValues_AreClassifiedExplicitly()
    {
        var relevant = new HashSet<EmailIntent>
        {
            EmailIntent.WorkCancellation,
            EmailIntent.VacationRequest,
            EmailIntent.DayOffWish,
            EmailIntent.AvailabilityAnnouncement,
            EmailIntent.ShiftPreference,
            EmailIntent.Other,
        };

        var nonRelevant = new HashSet<EmailIntent>
        {
            EmailIntent.CustomerMessage,
            EmailIntent.Unknown,
        };

        foreach (var intent in Enum.GetValues<EmailIntent>())
        {
            Assert.That(relevant.Contains(intent) || nonRelevant.Contains(intent), Is.True,
                $"EmailIntent.{intent} is not classified in either the relevant or non-relevant set of this tripwire test — add it.");

            var decision = ClarificationPolicy.Decide(Facts() with { Intent = intent });

            if (relevant.Contains(intent))
            {
                decision.Kind.ShouldBe(ClarificationDecisionKind.Ask);
            }
            else
            {
                decision.ShouldBe(ClarificationDecision.Skip(ClarificationSkipReason.NotPlanningRelevant));
            }
        }
    }
}
