// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Per-language tests for ClarificationQuestionGuard across all 25 shipped languages: three normal attendance
/// questions per language (late shift with times, "are you sick and cannot come tomorrow", a date range) and
/// the common sick-leave phrasings must pass the whole guard (length, sentence count, question mark of the
/// language, health terms of every language at once), while a fever question and a doctor question per
/// language (plus a compound case for Dutch, Danish, Norwegian, Swedish and Finnish) must be rejected as
/// health questions. The non-core phrasings are LLM translations pending native-speaker review.
/// </summary>

using Klacks.Api.Domain.Services.Inbound;

namespace Klacks.UnitTest.Domain.Services.Inbound;

[TestFixture]
public class ClarificationQuestionGuardLanguageTests
{
    [TestCase("de", "Kannst du heute deinen Spätdienst (14:00–22:00) arbeiten?")]
    [TestCase("de", "Bist du krank und kannst morgen nicht zu deiner Schicht kommen?")]
    [TestCase("de", "Kannst du vom 24.09. bis 26.09. arbeiten?")]
    [TestCase("en", "Can you work your late shift today (14:00–22:00)?")]
    [TestCase("en", "Are you sick and can't come to your shift tomorrow?")]
    [TestCase("en", "Can you work from 24.09. to 26.09.?")]
    [TestCase("fr", "Peux-tu faire ton service du soir aujourd'hui (14:00–22:00) ?")]
    [TestCase("fr", "Es-tu malade et ne peux-tu pas venir à ton service demain ?")]
    [TestCase("fr", "Peux-tu travailler du 24.09. au 26.09. ?")]
    [TestCase("it", "Puoi fare il tuo turno serale oggi (14:00–22:00)?")]
    [TestCase("it", "Sei malato e non puoi venire al tuo turno domani?")]
    [TestCase("it", "Puoi lavorare dal 24.09. al 26.09.?")]
    [TestCase("ar", "هل يمكنك العمل في نوبتك المسائية اليوم (14:00–22:00)؟")]
    [TestCase("ar", "هل أنت مريض ولا تستطيع الحضور إلى نوبتك غدًا؟")]
    [TestCase("ar", "هل يمكنك العمل من 24.09. إلى 26.09.؟")]
    [TestCase("cs", "Můžeš dnes odpracovat svou odpolední směnu (14:00–22:00)?")]
    [TestCase("cs", "Jsi nemocný a nemůžeš zítra přijít na směnu?")]
    [TestCase("cs", "Můžeš pracovat od 24.09. do 26.09.?")]
    [TestCase("da", "Kan du tage din aftenvagt i dag (14:00–22:00)?")]
    [TestCase("da", "Er du syg og kan ikke komme til din vagt i morgen?")]
    [TestCase("da", "Kan du arbejde fra 24.09. til 26.09.?")]
    [TestCase("el", "Μπορείς να δουλέψεις την απογευματινή βάρδια σου σήμερα (14:00–22:00);")]
    [TestCase("el", "Είσαι άρρωστος και δεν μπορείς να έρθεις στη βάρδια σου αύριο;")]
    [TestCase("el", "Μπορείς να δουλέψεις από 24.09. έως 26.09.;")]
    [TestCase("es", "¿Puedes hacer tu turno de tarde hoy (14:00–22:00)?")]
    [TestCase("es", "¿Estás enfermo y no puedes venir a tu turno mañana?")]
    [TestCase("es", "¿Puedes trabajar del 24.09. al 26.09.?")]
    [TestCase("fi", "Voitko tehdä iltavuorosi tänään (14:00–22:00)?")]
    [TestCase("fi", "Oletko sairas etkä pääse huomenna vuoroosi?")]
    [TestCase("fi", "Voitko tehdä töitä 24.09.–26.09.?")]
    [TestCase("he", "האם תוכל לעבוד היום במשמרת הערב שלך (14:00–22:00)?")]
    [TestCase("he", "האם אתה חולה ולא תוכל להגיע למשמרת שלך מחר?")]
    [TestCase("he", "האם תוכל לעבוד מ-24.09. עד 26.09.?")]
    [TestCase("id", "Apakah kamu bisa masuk shift sore hari ini (14:00–22:00)?")]
    [TestCase("id", "Apakah kamu sakit dan tidak bisa datang ke shift besok?")]
    [TestCase("id", "Apakah kamu bisa bekerja dari 24.09. sampai 26.09.?")]
    [TestCase("ja", "今日の遅番（14:00～22:00）に勤務できますか？")]
    [TestCase("ja", "病気で明日のシフトに来られないということですか？")]
    [TestCase("ja", "24.09.から26.09.まで勤務できますか？")]
    [TestCase("ko", "오늘 늦은 근무(14:00–22:00)를 할 수 있나요?")]
    [TestCase("ko", "아파서 내일 근무에 못 오는 건가요?")]
    [TestCase("ko", "24.09.부터 26.09.까지 근무할 수 있나요?")]
    [TestCase("ms", "Bolehkah anda bekerja syif petang anda hari ini (14:00–22:00)?")]
    [TestCase("ms", "Adakah anda sakit dan tidak dapat datang ke syif anda esok?")]
    [TestCase("ms", "Bolehkah anda bekerja dari 24.09. hingga 26.09.?")]
    [TestCase("nb", "Kan du ta kveldsvakten din i dag (14:00–22:00)?")]
    [TestCase("nb", "Er du syk og kan ikke komme på vakten din i morgen?")]
    [TestCase("nb", "Kan du jobbe fra 24.09. til 26.09.?")]
    [TestCase("nl", "Kun je vandaag je late dienst (14:00–22:00) werken?")]
    [TestCase("nl", "Ben je ziek en kun je morgen niet naar je dienst komen?")]
    [TestCase("nl", "Kun je van 24.09. tot 26.09. werken?")]
    [TestCase("pl", "Czy możesz dziś przyjść na swoją popołudniową zmianę (14:00–22:00)?")]
    [TestCase("pl", "Czy jesteś chory i nie możesz jutro przyjść na zmianę?")]
    [TestCase("pl", "Czy możesz pracować od 24.09. do 26.09.?")]
    [TestCase("pt", "Podes fazer o teu turno da tarde hoje (14:00–22:00)?")]
    [TestCase("pt", "Estás doente e não podes vir ao teu turno amanhã?")]
    [TestCase("pt", "Podes trabalhar de 24.09. a 26.09.?")]
    [TestCase("ro", "Poți lucra tura de după-amiază azi (14:00–22:00)?")]
    [TestCase("ro", "Ești bolnav și nu poți veni mâine la tură?")]
    [TestCase("ro", "Poți lucra de pe 24.09. până pe 26.09.?")]
    [TestCase("sv", "Kan du jobba ditt kvällspass i dag (14:00–22:00)?")]
    [TestCase("sv", "Är du sjuk och kan inte komma till ditt pass i morgon?")]
    [TestCase("sv", "Kan du jobba från 24.09. till 26.09.?")]
    [TestCase("th", "วันนี้คุณทำงานกะบ่าย (14:00–22:00) ได้ไหม?")]
    [TestCase("th", "คุณป่วยและมาทำงานกะพรุ่งนี้ไม่ได้ใช่ไหม?")]
    [TestCase("th", "คุณทำงานตั้งแต่วันที่ 24.09. ถึง 26.09. ได้ไหม?")]
    [TestCase("vi", "Hôm nay bạn có thể làm ca chiều (14:00–22:00) không?")]
    [TestCase("vi", "Bạn bị ốm và không thể đến ca làm việc ngày mai phải không?")]
    [TestCase("vi", "Bạn có thể làm việc từ 24.09. đến 26.09. không?")]
    [TestCase("zh-CN", "你今天能上晚班（14:00–22:00）吗？")]
    [TestCase("zh-CN", "你是生病了，明天不能来上班吗？")]
    [TestCase("zh-CN", "你能从24.09.到26.09.上班吗？")]
    [TestCase("zh-TW", "你今天能上晚班（14:00–22:00）嗎？")]
    [TestCase("zh-TW", "你是生病了，明天不能來上班嗎？")]
    [TestCase("zh-TW", "你能從24.09.到26.09.上班嗎？")]
    public void AttendanceQuestion_StaysAllowed(string language, string question)
    {
        ClarificationQuestionGuard.IsAcceptable(question, out var violation).ShouldBeTrue($"{language}: {violation}");
    }

    [TestCase("ar", "هل أنت في إجازة مرضية ولا تستطيع الحضور إلى نوبتك غدًا؟")]
    [TestCase("ar", "هل ما زلت في الإجازة المرضية اليوم؟")]
    [TestCase("cs", "Jsi na nemocenské a nemůžeš zítra přijít na směnu?")]
    [TestCase("da", "Er du sygemeldt og kan ikke komme til din vagt i morgen?")]
    [TestCase("el", "Είσαι σε άδεια ασθενείας και δεν μπορείς να έρθεις στη βάρδια σου αύριο;")]
    [TestCase("es", "¿Estás de baja por enfermedad y no puedes venir a tu turno mañana?")]
    [TestCase("es", "¿Estás de baja médica mañana?")]
    [TestCase("fi", "Oletko sairauslomalla etkä pääse huomenna vuoroosi?")]
    [TestCase("fi", "Onko sinulla sairauspoissaolo huomenna?")]
    [TestCase("he", "האם אתה בחופשת מחלה ולא תוכל להגיע למשמרת שלך מחר?")]
    [TestCase("he", "האם לקחת יום מחלה היום?")]
    [TestCase("id", "Apakah kamu cuti sakit dan tidak bisa datang ke shift besok?")]
    [TestCase("ja", "病欠で明日のシフトに来られないということですか？")]
    [TestCase("ko", "병가 중이라서 내일 근무에 못 오는 건가요?")]
    [TestCase("ms", "Adakah anda bercuti sakit dan tidak dapat datang ke syif anda esok?")]
    [TestCase("nb", "Er du sykemeldt og kan ikke komme på vakten din i morgen?")]
    [TestCase("nl", "Ben je ziekgemeld en kun je morgen niet naar je dienst komen?")]
    [TestCase("nl", "Heb je ziekteverlof en kun je morgen niet komen?")]
    [TestCase("nl", "Zit je in de Ziektewet en kun je morgen niet komen?")]
    [TestCase("pl", "Czy jesteś na zwolnieniu lekarskim i nie możesz jutro przyjść na zmianę?")]
    [TestCase("pl", "Czy jesteś na chorobowym i nie możesz jutro przyjść?")]
    [TestCase("pt", "Estás de baixa por doença e não podes vir ao teu turno amanhã?")]
    [TestCase("pt", "Você está de licença por doença e não pode vir amanhã?")]
    [TestCase("pt", "Você está de licença médica e não pode vir ao seu turno amanhã?")]
    [TestCase("ro", "Ești în concediu medical și nu poți veni mâine la tură?")]
    [TestCase("ro", "Ești în concediu de boală și nu poți veni mâine?")]
    [TestCase("sv", "Är du sjukskriven och kan inte komma till ditt pass i morgon?")]
    [TestCase("th", "คุณลาป่วยและมาทำงานกะพรุ่งนี้ไม่ได้ใช่ไหม?")]
    [TestCase("vi", "Bạn đang nghỉ ốm và không thể đến ca làm việc ngày mai phải không?")]
    [TestCase("zh-CN", "你是请病假了，明天不能来上班吗？")]
    [TestCase("zh-TW", "你是請病假了，明天不能來上班嗎？")]
    public void SickLeavePhrasing_StaysAllowed(string language, string question)
    {
        ClarificationQuestionGuard.IsAcceptable(question, out var violation).ShouldBeTrue($"{language}: {violation}");
    }

    [TestCase("ar", "هل لديك حمى؟")]
    [TestCase("ar", "هل ذهبت إلى الطبيب؟")]
    [TestCase("cs", "Máš horečku?")]
    [TestCase("cs", "Byl jsi u lékaře?")]
    [TestCase("da", "Har du feber?")]
    [TestCase("da", "Har du været hos lægen?")]
    [TestCase("da", "Har du hovedpine?")]
    [TestCase("da", "Har du rygsmerter?")]
    [TestCase("el", "Έχεις πυρετό;")]
    [TestCase("el", "Πήγες στον γιατρό;")]
    [TestCase("es", "¿Tienes fiebre?")]
    [TestCase("es", "¿Has ido al médico?")]
    [TestCase("fi", "Onko sinulla kuumetta?")]
    [TestCase("fi", "Kävitkö lääkärissä?")]
    [TestCase("fi", "Onko sinulla päänsärkyä?")]
    [TestCase("fi", "Onko sinulla selkäkipuja?")]
    [TestCase("he", "האם יש לך חום גבוה?")]
    [TestCase("he", "היית אצל רופא?")]
    [TestCase("id", "Apakah kamu demam?")]
    [TestCase("id", "Apakah kamu sudah ke dokter?")]
    [TestCase("ja", "熱がありますか？")]
    [TestCase("ja", "病院に行きましたか？")]
    [TestCase("ko", "열이 나나요?")]
    [TestCase("ko", "병원에 다녀왔나요?")]
    [TestCase("ms", "Adakah anda demam?")]
    [TestCase("ms", "Sudahkah anda berjumpa doktor?")]
    [TestCase("nb", "Har du feber?")]
    [TestCase("nb", "Har du vært hos fastlegen?")]
    [TestCase("nb", "Har du hodepine?")]
    [TestCase("nb", "Har du ryggsmerter?")]
    [TestCase("nl", "Heb je koorts?")]
    [TestCase("nl", "Ben je bij de huisarts geweest?")]
    [TestCase("nl", "Heb je hoofdpijn?")]
    [TestCase("nl", "Heb je rugpijn?")]
    [TestCase("pl", "Czy masz gorączkę?")]
    [TestCase("pl", "Czy byłeś u lekarza?")]
    [TestCase("pt", "Você está com febre?")]
    [TestCase("pt", "Foste ao médico?")]
    [TestCase("ro", "Ai febră?")]
    [TestCase("ro", "Ai fost la medic?")]
    [TestCase("sv", "Har du feber?")]
    [TestCase("sv", "Har du varit hos läkaren?")]
    [TestCase("sv", "Har du huvudvärk?")]
    [TestCase("sv", "Har du ryggsmärtor?")]
    [TestCase("th", "คุณมีไข้ไหม?")]
    [TestCase("th", "คุณไปหาหมอมาแล้วหรือยัง?")]
    [TestCase("vi", "Bạn có bị sốt không?")]
    [TestCase("vi", "Bạn đã đi khám bác sĩ chưa?")]
    [TestCase("zh-CN", "你发烧了吗？")]
    [TestCase("zh-CN", "你去看医生了吗？")]
    [TestCase("zh-TW", "你發燒了嗎？")]
    [TestCase("zh-TW", "你去看醫生了嗎？")]
    public void HealthQuestion_IsRejected(string language, string question)
    {
        ClarificationQuestionGuard.IsAcceptable(question, out var violation).ShouldBeFalse(language);
        violation.ShouldStartWith(ClarificationQuestionGuard.HealthTermViolationPrefix, customMessage: language);
    }
}
