// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Unit tests for EmailReplySender: the recipient is the client's stored address (never the sender
/// header), the subject gets a single "Re: " and is flattened to one line, a subject that looks
/// suspicious (a link, a MIME encoded-word marker, an '@' or a phone-like digit run) falls back to a
/// neutral fixed subject instead of reflecting it, and the resulting subject is bounded to
/// MaxReplySubjectLength, truncated at a word boundary. In-Reply-To/References thread the reply onto the
/// original mail (only strictly valid message ids within MaxMessageIdLength; synthetic ids without '@',
/// ids carrying line breaks or whitespace, and ids over the length limit are dropped; References keeps
/// only the last MaxReferencesCount ids). Every reply carries Auto-Submitted: auto-replied, and SMTP
/// failures, an unavailable mail service or exceptions map to a failed result, never an exception.
/// </summary>

using System.Diagnostics;
using Klacks.Api.Domain.Constants;
using Klacks.Api.Domain.Interfaces.Email;
using Klacks.Api.Domain.Models.Inbound;
using Klacks.Api.Infrastructure.Email;
using Klacks.Api.Infrastructure.Inbound;
using Microsoft.Extensions.Logging;

namespace Klacks.UnitTest.Infrastructure.Inbound;

[TestFixture]
public class EmailReplySenderTests
{
    private const int PathologicalShortRepeats = 20;
    private const int PathologicalLongRepeats = 40;
    private const int HugeSubjectLength = 1_000_000;

    private static readonly Guid ClientId = Guid.NewGuid();

    private IEmailClientAssignmentService _assignmentService = null!;
    private IEmailService _emailService = null!;
    private EmailReplySender _sender = null!;

    [SetUp]
    public void SetUp()
    {
        _assignmentService = Substitute.For<IEmailClientAssignmentService>();
        _emailService = Substitute.For<IEmailService>();
        _emailService.CanSendEmailAsync().Returns(true);
        _sender = new EmailReplySender(_assignmentService, _emailService, Substitute.For<ILogger<EmailReplySender>>());
    }

    private static ClarificationRequest Request(
        string subject = "Krank",
        string messageId = "original-1@example.com",
        string? threadReferences = "older-1@example.com") => new(
        ClientId: ClientId,
        ClientType: EntityTypeEnum.Employee,
        Source: new InboundSource(
            SourceId: Guid.NewGuid(),
            SourceKind: InboundSourceKind.Email,
            Channel: "Email",
            SenderDisplay: "Anna Muster (anna@example.com)",
            Subject: subject,
            Body: "Ich fühle mich nicht gut.",
            ReceivedAt: DateTime.UtcNow),
        ReplyChannel: "Email",
        SenderAddress: "anna@example.com",
        EmailThread: new ClarificationEmailThread(
            MessageId: messageId,
            InReplyTo: null,
            ThreadReferences: threadReferences,
            IsAutoGenerated: false));

    private static InboundReplyTarget Target(string? inReplyTo = null, string? references = null) => new(
        Recipient: "anna@example.com",
        Subject: "Re: Krank",
        InReplyTo: inReplyTo,
        References: references);

    [Test]
    public void SourceKind_IsEmail()
    {
        _sender.SourceKind.ShouldBe(InboundSourceKind.Email);
    }

    [Test]
    public async Task ResolveTarget_UsesStoredAddressAndThreadHeaders()
    {
        _assignmentService.GetStoredAddressAsync(ClientId, "anna@example.com", Arg.Any<CancellationToken>()).Returns("Anna@Example.com");

        var target = await _sender.ResolveTargetAsync(Request());

        target.ShouldNotBeNull();
        target.Recipient.ShouldBe("Anna@Example.com");
        target.Subject.ShouldBe("Re: Krank");
        target.InReplyTo.ShouldBe("<original-1@example.com>");
        target.References.ShouldBe("<older-1@example.com> <original-1@example.com>");
    }

    [Test]
    public async Task ResolveTarget_NoStoredAddress_ReturnsNull()
    {
        _assignmentService.GetStoredAddressAsync(ClientId, Arg.Any<string>(), Arg.Any<CancellationToken>()).Returns((string?)null);

        (await _sender.ResolveTargetAsync(Request())).ShouldBeNull();
    }

    [Test]
    public async Task ResolveTarget_SyntheticMessageId_HasNoThreadHeaders()
    {
        _assignmentService.GetStoredAddressAsync(ClientId, Arg.Any<string>(), Arg.Any<CancellationToken>()).Returns("anna@example.com");

        var target = await _sender.ResolveTargetAsync(Request(messageId: "INBOX-42", threadReferences: null));

        target!.InReplyTo.ShouldBeNull();
        target.References.ShouldBeNull();
    }

    [TestCase("original-1@example.com\r\nBcc: evil@example.org")]
    [TestCase("original-1@example.com\n")]
    [TestCase("original-1@example.com\r")]
    [TestCase("original 1@example.com")]
    [TestCase("<original-1@exa<mple.com>")]
    [TestCase("orig\u00e4nal@example.com")]
    public async Task ResolveTarget_MessageIdWithLineBreakOrInvalidCharacters_HasNoInReplyTo(string messageId)
    {
        _assignmentService.GetStoredAddressAsync(ClientId, Arg.Any<string>(), Arg.Any<CancellationToken>()).Returns("anna@example.com");

        var target = await _sender.ResolveTargetAsync(Request(messageId: messageId, threadReferences: null));

        target!.InReplyTo.ShouldBeNull();
        target.References.ShouldBeNull();
    }

    [Test]
    public async Task ResolveTarget_MessageIdLongerThanLimit_HasNoInReplyTo()
    {
        _assignmentService.GetStoredAddressAsync(ClientId, Arg.Any<string>(), Arg.Any<CancellationToken>()).Returns("anna@example.com");
        var tooLong = new string('a', InboundClarificationConstants.MaxMessageIdLength) + "@example.com";

        var target = await _sender.ResolveTargetAsync(Request(messageId: tooLong, threadReferences: null));

        target!.InReplyTo.ShouldBeNull();
        target.References.ShouldBeNull();
    }

    [Test]
    public void BuildReferences_DropsInvalidTokensAndKeepsValidOnes()
    {
        var thread = new ClarificationEmailThread(
            MessageId: "original-1@example.com",
            InReplyTo: null,
            ThreadReferences: "<older-1@example.com> garbage <in<valid@example.com> older-2@example.com <older-1@example.com>",
            IsAutoGenerated: false);

        EmailReplySender.BuildReferences(thread)
            .ShouldBe("<older-1@example.com> <older-2@example.com> <original-1@example.com>");
    }

    [TestCase("<older-1@example.com> <x@y\r\nBcc: evil@example.org>")]
    [TestCase("<older-1@example.com>\n<evil@example.org>")]
    [TestCase("<older-1@example.com>\t<evil@example.org>")]
    public void BuildReferences_ReferencesWithLineBreakOrControlCharacters_AreDiscardedAsAWhole(string poisoned)
    {
        var thread = new ClarificationEmailThread(
            MessageId: "original-1@example.com",
            InReplyTo: null,
            ThreadReferences: poisoned,
            IsAutoGenerated: false);

        EmailReplySender.BuildReferences(thread).ShouldBe("<original-1@example.com>");
    }

    [Test]
    public void BuildReferences_MessageIdLongerThanLimit_IsDropped()
    {
        var tooLong = new string('a', InboundClarificationConstants.MaxMessageIdLength) + "@example.com";
        var thread = new ClarificationEmailThread(
            MessageId: "original-1@example.com",
            InReplyTo: null,
            ThreadReferences: tooLong,
            IsAutoGenerated: false);

        EmailReplySender.BuildReferences(thread).ShouldBe("<original-1@example.com>");
    }

    [Test]
    public void BuildReferences_MoreThanMaxCountValidIds_KeepsOnlyTheLastOnes()
    {
        var referencedIds = Enumerable.Range(1, InboundClarificationConstants.MaxReferencesCount + 2)
            .Select(i => $"id-{i}@example.com");
        var thread = new ClarificationEmailThread(
            MessageId: "original-1@example.com",
            InReplyTo: null,
            ThreadReferences: string.Join(' ', referencedIds),
            IsAutoGenerated: false);

        var result = EmailReplySender.BuildReferences(thread);

        var ids = result!.Split(' ');
        ids.Length.ShouldBe(InboundClarificationConstants.MaxReferencesCount);
        ids[0].ShouldBe("<id-4@example.com>");
        ids[^1].ShouldBe("<original-1@example.com>");
    }

    [TestCase("Re: Krank", "Re: Krank")]
    [TestCase("RE: Krank", "RE: Krank")]
    [TestCase("Krank", "Re: Krank")]
    [TestCase("", "Re: ")]
    [TestCase(null, "Re: ")]
    public void BuildSubject_AddsReOnlyOnce(string? original, string expected)
    {
        EmailReplySender.BuildSubject(original).ShouldBe(expected);
    }

    [TestCase("Krank\u0085heute\u2028morgen\u2029ab", "Re: Krank heute morgen ab")]
    [TestCase("Krank\u0000 \u0007  heute", "Re: Krank heute")]
    [TestCase("Krank\u202eheute", "Re: Krank heute")]
    public void BuildSubject_FlattensLineBreaksAndControlCharactersToOneLine(string original, string expected)
    {
        EmailReplySender.BuildSubject(original).ShouldBe(expected);
    }

    [TestCase("Krank\r\nBcc: evil@example.org")]
    [TestCase("Best\u00e4tige bitte unter https://example.com")]
    [TestCase("Siehe www.example.com")]
    [TestCase("=?UTF-8?B?SGVsbG8=?=")]
    [TestCase("Ruf mich an unter 076 123 45 67")]
    public void BuildSubject_SuspiciousOriginal_FallsBackToNeutralSubject(string original)
    {
        EmailReplySender.BuildSubject(original).ShouldBe(InboundClarificationConstants.NeutralReplySubject);
    }

    [Test]
    public void BuildSubject_DateAndTimeOnly_IsNotTreatedAsSuspicious()
    {
        EmailReplySender.BuildSubject("Termin am 24.09.2026 14:00").ShouldBe("Re: Termin am 24.09.2026 14:00");
    }

    [Test]
    public void BuildSubject_LongOriginal_IsTruncatedAtWordBoundaryWithinMaxLength()
    {
        var original = string.Join(' ', Enumerable.Range(1, 20).Select(i => $"Wort{i}"));

        var subject = EmailReplySender.BuildSubject(original);
        var untruncated = InboundClarificationConstants.ReplySubjectPrefix + original;

        subject.Length.ShouldBeLessThanOrEqualTo(InboundClarificationConstants.MaxReplySubjectLength);
        untruncated.Length.ShouldBeGreaterThan(InboundClarificationConstants.MaxReplySubjectLength);
        untruncated.ShouldStartWith(subject);
        subject.ShouldNotEndWith(" ");
        untruncated[subject.Length].ShouldBe(' ');
    }

    [Test]
    public void BuildSubject_OverlappingDateTokensFollowedByAnInvalidTime_DoesNotBlockAndFallsBackToNeutralSubject()
    {
        var original = string.Concat(Enumerable.Repeat("23.09.2026 ", PathologicalShortRepeats)) + "1:99";
        var stopwatch = Stopwatch.StartNew();

        var subject = EmailReplySender.BuildSubject(original);

        stopwatch.Elapsed.ShouldBeLessThan(TimeSpan.FromSeconds(1));
        subject.ShouldBe(InboundClarificationConstants.NeutralReplySubject);
    }

    [Test]
    public void BuildSubject_PathologicalDateRunBeyondTheInspectionBound_DoesNotBlockAndStaysWithinMaxLength()
    {
        var original = string.Concat(Enumerable.Repeat("23.09.2026 ", PathologicalLongRepeats)) + "1:99";
        var stopwatch = Stopwatch.StartNew();

        var subject = EmailReplySender.BuildSubject(original);

        stopwatch.Elapsed.ShouldBeLessThan(TimeSpan.FromSeconds(1));
        subject.Length.ShouldBeLessThanOrEqualTo(InboundClarificationConstants.MaxReplySubjectLength);
        subject.ShouldNotContain("1:99");
    }

    [Test]
    public void BuildSubject_HugeSubject_IsBoundedBeforeInspection()
    {
        var original = new string('1', HugeSubjectLength) + " ";
        var stopwatch = Stopwatch.StartNew();

        var subject = EmailReplySender.BuildSubject(original);

        stopwatch.Elapsed.ShouldBeLessThan(TimeSpan.FromSeconds(1));
        subject.ShouldBe(InboundClarificationConstants.NeutralReplySubject);
    }

    [Test]
    public void BuildSubject_SuspiciousContentBeyondTheSentPart_IsNeverSent()
    {
        var original = string.Join(' ', Enumerable.Repeat("Wort", 100)) + " https://evil.example";

        var subject = EmailReplySender.BuildSubject(original);

        subject.Length.ShouldBeLessThanOrEqualTo(InboundClarificationConstants.MaxReplySubjectLength);
        subject.ShouldNotContain("evil");
        subject.ShouldNotContain("://");
    }

    [Test]
    public void BuildSubject_SuspiciousContentInsideTheSentPart_StillFallsBackWhenTheSubjectIsLong()
    {
        var original = "Ruf mich an 076 123 45 67 " + string.Join(' ', Enumerable.Repeat("Wort", 100));

        EmailReplySender.BuildSubject(original).ShouldBe(InboundClarificationConstants.NeutralReplySubject);
    }

    [Test]
    public void BuildSubject_InjectedSubject_FallsBackToNeutralSubject()
    {
        var wrapper = new EmailWrapper { ReplyTo = "klacks@example.com" };

        using var message = wrapper.BuildReplyMessage(
            "anna@example.com",
            EmailReplySender.BuildSubject("Krank\r\nBcc: evil@example.org"),
            "Frage?",
            new Dictionary<string, string>());

        message.ShouldNotBeNull();
        message.Subject.ShouldBe(InboundClarificationConstants.NeutralReplySubject);
        message.Bcc.ShouldBeEmpty();
    }

    [Test]
    public async Task Send_PassesThreadHeadersAndAutoSubmitted()
    {
        IReadOnlyDictionary<string, string>? capturedHeaders = null;
        _emailService.SendReplyMail(
                "anna@example.com", "Re: Krank", "Kannst du heute nicht arbeiten?",
                Arg.Do<IReadOnlyDictionary<string, string>>(h => capturedHeaders = h))
            .Returns("true");

        var result = await _sender.SendAsync(
            Request(), Target(inReplyTo: "<original-1@example.com>", references: "<original-1@example.com>"), "Kannst du heute nicht arbeiten?");

        result.Success.ShouldBeTrue();
        capturedHeaders.ShouldNotBeNull();
        capturedHeaders["Auto-Submitted"].ShouldBe("auto-replied");
        capturedHeaders["In-Reply-To"].ShouldBe("<original-1@example.com>");
        capturedHeaders["References"].ShouldBe("<original-1@example.com>");
    }

    [Test]
    public async Task Send_WithoutThreadHeaders_StillCarriesAutoSubmitted()
    {
        IReadOnlyDictionary<string, string>? capturedHeaders = null;
        _emailService.SendReplyMail(
                Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>(),
                Arg.Do<IReadOnlyDictionary<string, string>>(h => capturedHeaders = h))
            .Returns("true");

        await _sender.SendAsync(Request(), Target(), "Frage?");

        capturedHeaders.ShouldNotBeNull();
        capturedHeaders.Keys.ShouldBe(new[] { "Auto-Submitted" });
    }

    [Test]
    public async Task Send_SmtpError_IsAFailedResult()
    {
        _emailService.SendReplyMail(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>(), Arg.Any<IReadOnlyDictionary<string, string>>())
            .Returns("Mailbox unavailable");

        var result = await _sender.SendAsync(Request(), Target(), "Frage?");

        result.Success.ShouldBeFalse();
        result.Error.ShouldBe("Mailbox unavailable");
    }

    [Test]
    public async Task Send_MailServiceUnavailable_IsAFailedResult()
    {
        _emailService.CanSendEmailAsync().Returns(false);

        var result = await _sender.SendAsync(Request(), Target(), "Frage?");

        result.Success.ShouldBeFalse();
        _emailService.DidNotReceiveWithAnyArgs().SendReplyMail(default!, default!, default!, default!);
    }

    [Test]
    public async Task Send_Throws_IsAFailedResultNotAnException()
    {
        _emailService.SendReplyMail(Arg.Any<string>(), Arg.Any<string>(), Arg.Any<string>(), Arg.Any<IReadOnlyDictionary<string, string>>())
            .Returns(_ => throw new InvalidOperationException("smtp down"));

        var result = await _sender.SendAsync(Request(), Target(), "Frage?");

        result.Success.ShouldBeFalse();
        result.Error.ShouldBe("smtp down");
    }

    [Test]
    public async Task Send_HeaderValueWithLineBreak_IsAFailedResultAndNothingIsSent()
    {
        var result = await _sender.SendAsync(
            Request(), Target(inReplyTo: "<original-1@example.com>\r\nBcc: evil@example.org"), "Frage?");

        result.Success.ShouldBeFalse();
        _emailService.DidNotReceiveWithAnyArgs().SendReplyMail(default!, default!, default!, default!);
    }

    [Test]
    public async Task Send_RecipientWithLineBreak_IsAFailedResultAndNothingIsSent()
    {
        var target = new InboundReplyTarget(
            Recipient: "anna@example.com\r\nBcc: evil@example.org",
            Subject: "Re: Krank",
            InReplyTo: null,
            References: null);

        var result = await _sender.SendAsync(Request(), target, "Frage?");

        result.Success.ShouldBeFalse();
        _emailService.DidNotReceiveWithAnyArgs().SendReplyMail(default!, default!, default!, default!);
    }
}
