// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Pins the Npgsql translation of the fitness join. The behavioural tests of the same three methods run
/// on the in-memory provider, which evaluates the sub-select in memory and would stay green even if the
/// relational translation stopped emitting it - and a sub-select that quietly disappears restores the
/// bug it was written for: every late UiAction failure would count as a success again. The model is
/// built against Npgsql without ever opening a connection, because ToQueryString generates the SQL
/// offline and the in-memory provider has no SQL to show.
/// </summary>

using System.Globalization;
using System.Text.RegularExpressions;
using Klacks.Api.Domain.Enums;
using Klacks.Api.Infrastructure.Persistence;
using Klacks.Api.Infrastructure.Repositories.Assistant;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using NSubstitute;
using NUnit.Framework;
using Shouldly;

namespace Klacks.UnitTest.Infrastructure.Repositories.Assistant;

[TestFixture]
public class SkillSelectionTrajectoryFitnessSqlTests
{
    private const string UnusedConnectionString = "Host=localhost;Database=unused;Username=u;Password=p";
    private const string UsageTable = "skill_usage_records";
    private const string OwnerName = "create_client";
    private const string RecipeName = "onboard_client";
    private const string WhitespaceRuns = @"\s+";
    private const string SingleSpace = " ";

    private static readonly DateTime WindowStartUtc = new(2026, 9, 1, 0, 0, 0, DateTimeKind.Utc);

    private static readonly string DispatchedValue =
        ((int)UiActionStatus.Dispatched).ToString(CultureInfo.InvariantCulture);

    // The alias of the sub-select is generated by the provider, so it is captured instead of spelled
    // out; binding all three predicates to that same capture is what proves they belong to the
    // sub-select and not to the outer query, which carries a turn_id test of its own.
    private static readonly Regex FailedTurnSubSelect = new(
        $@"FROM {UsageTable} AS (?<alias>\w+) WHERE .*?"
        + @"\k<alias>\.turn_id IS NOT NULL.*?"
        + $@"\k<alias>\.ui_action_status IS NULL OR \k<alias>\.ui_action_status <> {DispatchedValue}");

    private DataBaseContext _context = null!;
    private SkillSelectionTrajectoryRepository _repository = null!;

    [SetUp]
    public void SetUp()
    {
        var options = new DbContextOptionsBuilder<DataBaseContext>()
            .UseNpgsql(UnusedConnectionString)
            .UseSnakeCaseNamingConvention()
            .Options;

        _context = new DataBaseContext(options, Substitute.For<IHttpContextAccessor>());
        _repository = new SkillSelectionTrajectoryRepository(_context);
    }

    [TearDown]
    public void TearDown() => _context.Dispose();

    [Test]
    public void PhraseUsage_AsksTheDatabaseForTheFailedTurnsOfTheUsageRecords() =>
        AssertTheSubSelectSurvivedTranslation(
            _repository.PhraseUsageQuery(OwnerName, WindowStartUtc).ToQueryString());

    [Test]
    public void RecipeUsage_AsksTheDatabaseForTheFailedTurnsOfTheUsageRecords() =>
        AssertTheSubSelectSurvivedTranslation(
            _repository.RecipeUsageQuery(RecipeName, WindowStartUtc).ToQueryString());

    [Test]
    public void SuccessfulRecipeTurn_AsksTheDatabaseForTheFailedTurnsOfTheUsageRecords() =>
        AssertTheSubSelectSurvivedTranslation(
            _repository.SuccessfulRecipeTurnQuery(RecipeName).ToQueryString());

    [Test]
    public void FailedTurnIds_ReadsOnlyReportedFailuresAndNeverADispatchedRow()
    {
        var sql = Normalize(_repository.FailedTurnIds().ToQueryString());

        sql.ShouldContain($"FROM {UsageTable}");
        sql.ShouldContain("turn_id IS NOT NULL");
        sql.ShouldContain($"ui_action_status <> {DispatchedValue}");
    }

    private static void AssertTheSubSelectSurvivedTranslation(string sql)
    {
        var normalized = Normalize(sql);

        normalized.ShouldContain(UsageTable);
        FailedTurnSubSelect.IsMatch(normalized).ShouldBeTrue(
            $"The sub-select over {UsageTable} no longer pins turn_id IS NOT NULL and the "
            + $"ui_action_status predicate. Generated SQL: {normalized}");
    }

    private static string Normalize(string sql) => Regex.Replace(sql, WhitespaceRuns, SingleSpace);
}
