// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Unit tests for the IMAP-to-ReceivedEmail mapping of the mail threading headers (In-Reply-To,
/// References) and for EmailAutoGeneratedDetector, which marks auto-generated mail (Auto-Submitted other
/// than "no", Precedence bulk/list/junk, List-Id, X-Autoreply, X-Autorespond) so the clarification
/// dialog never asks back on an auto-reply or a mailing-list message.
/// </summary>

using Klacks.Api.Infrastructure.Email;
using MailKit;
using MimeKit;

namespace Klacks.UnitTest.Infrastructure.Email;

[TestFixture]
public class ImapEmailMappingTests
{
    private static MimeMessage Message()
    {
        var message = new MimeMessage();
        message.From.Add(new MailboxAddress("Anna Muster", "anna@example.com"));
        message.To.Add(new MailboxAddress("Klacks", "klacks@example.com"));
        message.Subject = "Re: Rückfrage";
        message.Body = new TextPart("plain") { Text = "Ja, ich kann heute nicht kommen." };
        return message;
    }

    [Test]
    public void MapToReceivedEmail_CopiesThreadingHeadersWithoutBrackets()
    {
        var message = Message();
        message.InReplyTo = "question-1@klacks.example";
        message.References.Add("original-1@example.com");
        message.References.Add("question-1@klacks.example");

        var email = ImapEmailService.MapToReceivedEmail(message, new UniqueId(7), "INBOX", "answer-1@example.com");

        email.InReplyTo.ShouldBe("question-1@klacks.example");
        email.ThreadReferences.ShouldBe("original-1@example.com question-1@klacks.example");
        email.IsAutoGenerated.ShouldBeFalse();
    }

    [Test]
    public void MapToReceivedEmail_WithoutThreadingHeaders_LeavesThemNull()
    {
        var email = ImapEmailService.MapToReceivedEmail(Message(), new UniqueId(8), "INBOX", "plain-1@example.com");

        email.InReplyTo.ShouldBeNull();
        email.ThreadReferences.ShouldBeNull();
    }

    [Test]
    public void MapToReceivedEmail_AutoReply_IsMarkedAutoGenerated()
    {
        var message = Message();
        message.Headers.Add("Auto-Submitted", "auto-replied");

        var email = ImapEmailService.MapToReceivedEmail(message, new UniqueId(9), "INBOX", "auto-1@example.com");

        email.IsAutoGenerated.ShouldBeTrue();
    }

    [TestCase("Auto-Submitted", "auto-replied", true)]
    [TestCase("Auto-Submitted", "auto-generated; owner-email=\"a@example.com\"", true)]
    [TestCase("Auto-Submitted", "no", false)]
    [TestCase("Auto-Submitted", "No ", false)]
    [TestCase("Precedence", "bulk", true)]
    [TestCase("Precedence", "list", true)]
    [TestCase("Precedence", "junk", true)]
    [TestCase("Precedence", "first-class", false)]
    [TestCase("List-Id", "<team.example.com>", true)]
    [TestCase("X-Autoreply", "yes", true)]
    [TestCase("X-Autorespond", "vacation", true)]
    [TestCase("X-Mailer", "Outlook", false)]
    public void IsAutoGenerated_EvaluatesTheHeader(string header, string value, bool expected)
    {
        var message = Message();
        message.Headers.Add(header, value);

        EmailAutoGeneratedDetector.IsAutoGenerated(message.Headers).ShouldBe(expected);
    }

    [Test]
    public void IsAutoGenerated_NoHeaders_IsFalse()
    {
        EmailAutoGeneratedDetector.IsAutoGenerated(Message().Headers).ShouldBeFalse();
    }
}
